### ISSUE TITLE
no event is triggered by UpdateReportedPropertiesAsync

### ISSUE THREAD

**Issue by pesetskyps** [xaviermignot/device-twin-routing-demo#1]
Hi I am trying to repeat the same exercise and downloaded your repo to try against my device
I sent the update and see them on the device itlsef.

![image](https://user-images.githubusercontent.com/6270100/120369144-89e5bc80-c31b-11eb-9fe8-538999a2ecbd.png)

I set no routing
But see no events that are triggered to reported properties update only for telemetry. 
Can you try from your side to check is it just my issues?
![image](https://user-images.githubusercontent.com/6270100/120369077-7b97a080-c31b-11eb-972b-9b6a7a4e0d5e.png)

**Comment by xaviermignot** [comment]
Hello,

Thanks for filling an issue it's the very first one across all my repos 😃 

Have you created a route on the IoT Hub to route the device twin changes ?
If not you can do it using the following command: 
`az iot hub route create --hub-name paveliothub001 -n route-device-twin-changes --source twinchangeevents --endpoint-name events`

And if you have already created the route what does the following command outputs on your side:
`az iot hub route list --hub-name paveliothub001`
?

**Comment by pesetskyps** [comment]
That is exactly what I was missing. Thank you very much! That's what happens when you work in the evening :)
Great article on very narrow topic. Helped me a lot!
